name: Build & Push invenio-rdm-starter 

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - pnnl-main

jobs:
  build-scan-push:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      working-directory: .
      buildx-version: 'v0.16.2'
      registry: pnnldp.azurecr.io
      image-tag: invenio-rdm-starter:latest
      push: true
      scan: true
      scan-ubuntufix: true
      fail-onvulnerability: false
    secrets:
      az-client-id: ${{ secrets.ACR_USERNAME }}
      az-client-secret: ${{ secrets.ACR_PASSWORD }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
